/**
 * Turns supabase/seed/products.json into the SQL that seeds public.products.
 *
 * Usage: node scripts/catalog-to-sql.mjs > supabase/migrations/000N_catalog_seed.sql
 *
 * The whole catalogue goes in as one jsonb document unpacked server-side with
 * jsonb_to_recordset, so there is no hand-rolled SQL escaping of 268 titles.
 * Output is deterministic (no timestamps), which lets CI diff it against the
 * committed migration. The upsert never touches user_rating_sum /
 * user_review_count: re-seeding must not erase what real shoppers wrote.
 */
import fs from "node:fs";

const products = JSON.parse(fs.readFileSync("supabase/seed/products.json", "utf8"));
const json = JSON.stringify(products);

const TAG = "$catalog$";
if (json.includes(TAG)) throw new Error(`catalogue contains the dollar-quote tag ${TAG}`);

const columns = [
  ["asin", "r.asin"],
  ["title", "r.title"],
  ["short_title", 'r."shortTitle"'],
  ["brand", "r.brand"],
  ["category", "r.category"],
  ["price_cents", 'r."priceCents"'],
  ["list_price_cents", 'r."listPriceCents"'],
  ["price_synthesised", 'coalesce(r."priceSynthesised", false)'],
  ["scraped_rating", "r.rating"],
  ["scraped_review_count", 'r."reviewCount"'],
  ["image", "r.image"],
  ["images", "array(select jsonb_array_elements_text(r.images))"],
  // The scrape calls it isPrime; on HAUL it is Express shipping.
  ["express", 'r."isPrime"'],
  ["badge", "r.badge"],
  ["bought_past_month", 'r."boughtPastMonth"'],
  ["bullets", "array(select jsonb_array_elements_text(r.bullets))"],
  ["stock", "r.stock"],
  ["variants", "r.variants"],
];

const recordset = [
  "asin text", "title text", '"shortTitle" text', "brand text", "category text",
  '"priceCents" int', '"listPriceCents" int', '"priceSynthesised" boolean',
  "rating numeric", '"reviewCount" int', "image text", "images jsonb",
  '"isPrime" boolean', "badge text", '"boughtPastMonth" int', "bullets jsonb",
  "stock int", "variants jsonb",
];

const updates = columns
  .filter(([c]) => c !== "asin")
  .map(([c]) => `  ${c} = excluded.${c},`)
  .join("\n");

process.stdout.write(`-- GENERATED by scripts/catalog-to-sql.mjs from supabase/seed/products.json.
-- Do not edit by hand: change the seed and generate a NEW migration instead.
-- ${products.length} products.

insert into public.products (
  ${columns.map(([c]) => c).join(", ")}
)
select
  ${columns.map(([, e]) => e).join(",\n  ")}
from jsonb_to_recordset(${TAG}${json}${TAG}::jsonb) as r(
  ${recordset.join(", ")}
)
on conflict (asin) do update set
${updates}
  updated_at = now();
`);
